<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="6VONETUM41T5TPY" name="com.vtiger.qa.testcases.IndexPageTestCases" tests="8" failures="1" timestamp="21 Jul 2020 07:37:28 GMT" time="31.798" errors="0">
  <testcase name="verifyTitle" time="0.050" classname="com.vtiger.qa.testcases.IndexPageTestCases"/>
  <testcase name="verifyLogo" time="0.336" classname="com.vtiger.qa.testcases.IndexPageTestCases"/>
  <testcase name="checkProductsDropdown" time="0.542" classname="com.vtiger.qa.testcases.IndexPageTestCases"/>
  <testcase name="verifyPricingLink" time="3.599" classname="com.vtiger.qa.testcases.IndexPageTestCases"/>
  <testcase name="checkResourcesDropdown" time="1.009" classname="com.vtiger.qa.testcases.IndexPageTestCases"/>
  <testcase name="verifyCovidLink" time="7.137" classname="com.vtiger.qa.testcases.IndexPageTestCases">
    <failure type="java.lang.AssertionError" message="expected [Login - Vtiger] but found [Covid-19: Vtiger&#039;s Business Assistance Package | Vtiger CRM]">
      <![CDATA[java.lang.AssertionError: expected [Login - Vtiger] but found [Covid-19: Vtiger's Business Assistance Package | Vtiger CRM]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.vtiger.qa.testcases.IndexPageTestCases.verifyCovidLink(IndexPageTestCases.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyCovidLink -->
  <testcase name="verifyLoginLink" time="8.660" classname="com.vtiger.qa.testcases.IndexPageTestCases"/>
  <testcase name="verifySignUpLink" time="10.465" classname="com.vtiger.qa.testcases.IndexPageTestCases"/>
</testsuite> <!-- com.vtiger.qa.testcases.IndexPageTestCases -->
